version: '3.8'

services:
  frontend:
    build: ./frontend
    ports:
      - "3000:80"  # Map port 3000 on the host to port 80 in the container
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Map port 5000 on the host to port 5000 in the container
    environment:
      MONGO_URI: mongodb://mongo:27017/mydb  # Connection string for MongoDB
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    networks:
      - app-network

networks:
  app-network:

volumes:
  mongo-data:
